devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: b085e192-f92c-40e4-a439-612afa79a44a
images:
    debug: sha256:0316fd6620b95fdd34d380608c45e729d5f072f94d000468b20d22495928ac88
    release: ''
imagetags:
    debug: cpphello_arm64v8-debian-no-ssh_bullseye_debug_b085e192-f92c-40e4-a439-612afa79a44a
    release: cpphello_arm64v8-debian-no-ssh_bullseye_release_b085e192-f92c-40e4-a439-612afa79a44a
modificationdate: '2022-08-10T14:09:26.891330'
networks:
    common: []
    debug: []
    release: []
otapackagename: ''
otapackageversion: 1.0.0
platformid: arm64v8-debian-no-ssh_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEAxjHFWfA+tZhXL8STLG1mdUlTUzEvp1eDGT225OtqTXhlSVde

    gb6I7PhkUV0HYdCtKPbNedjLEubg/Dys1zt3YO941niuRw+/HKa24sjbrgeNdOLt

    lKivUOh1FL/XDzTRg4WvAgF9KcHM1UKfIKWhNvYFSJsZpBvz7VCJ5cKHr/YCxgbT

    2M3SDwmxHxW4k11rTbN1t6TtOxe62j7iVJoz9MX1E1goRQteC/b9RS0DMo2nWMXs

    XbAr6e5DC5F3qJmcziRFVLoWo6zDamEs5UktLft8xOjHvOnBJBzbAoY7mwOwpMmy

    aMVvqMsmDvxauc4yW9HvmHk8ti+uBixwObhPIQIDAQABAoIBACfb9Bz/plj2o5gx

    gEjH0rqFTer2Aie1P6IoqXr2BnnAnBwpJFJTG64O0XwUicrIAT8zDYVzDnpFcRuB

    Z2Bc7wgReTum5yPW/KA6Ph8zdozUK4SFq/LBDwsmSP+sikeeX4GENfthCcdHWNbN

    8HtMHDVVup/Mw5Yf4gmI8EbDPe8q31pxeXafgLJHJlHWJY0kH+HmTclnr6YE235l

    jNJIrPnsOngwzCqlCiDWEz7yDyRTC5/YGZrJiTqzIuaBRElt+y9CUyjBYFBzS1b5

    knfsYi1ohsMR6lTold0X3KS8DJAT1GJFFCQRvAGDc9aiQWdTrczV03DyZzJZOeVA

    BOcbqo0CgYEA/D/jgRWJFrty1StJ9SPIX06MAMTFMinTsr/hdfF7qPAmtigFcoP3

    WwHkXiZL6S7DqeoaeD8EbZuOQo0cbUial5akLypWWWPfs2qtSEGJlAhJDPOfKg1Q

    +fWr0B9ppE27CBPxaR1u4bKN1WWxOpyuH+5HD9dPs9rSIHI6mJrPdxUCgYEAySQj

    QdLyx6eYxTzGD2JIpCQ1qAH7EA28SfYhZu67XTi4ZBT0uY/vGRd6+ZK4zBUP6K5U

    QUmCqxPhYaZh/Zh/URkJAXlCyCxVDAgEeHVegqoQz1GMe0bSLqslvWRyGZCMOhry

    rxPgzlWn4xluKe9zU4JdyHTKB2cOofU8dSYE+t0CgYEAk0Xd1wSyyEHitpCSmnws

    xXA/j0dS9omzHr6mrMyzbRvhDiLpo0VnCoxdP5bOZTM3a6HRmHj6ZeAXO8XVXfyw

    vWZnL15hkckc10ymJPSWlYYM2HH4cH3b1ERZ7qYYcKQtWXcDUGKt1ToBUyEPS3Ak

    vWHJvXbxAsn0OptWmLhx/k0CgYBfjEcjUa36oea0azY6wJl5P6otcSNucNfs2nrr

    hqSCmBsfj8ThETqnVLwaKlSWvbqc8ZMcoGruEbeSx5LtALAaOiZJCO1sYYLVAEn/

    XuHSeC8cDMULGo1lle+LlFePRVcXkw2NlYfI/G+QNdhbG2BRXzBltPTzp0UQMorR

    q4naEQKBgD9UfWh74M9mzH7WYHQxlYOIUzb34ckq8HhgoOTeuMNyzEVLJb2mbZXd

    KJsC/1d+KBepEfNYXtDQtHDpu8Mj7MHGx/KCNefFWdG/0V8m0XPdEbACEYL53F/Z

    Id1iKamxnxaSpa6pgBm5IUPH8wxuU2AwBUMJl6pR0g7dyO2Cg1P4

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appname: cpphello
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        exename: bin/cpphello
        expose: ''
        extrapackages: ''
        language: c-cpp-nossh
        preinstallcommands: ''
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGMcVZ8D61mFcvxJMsbWZ1SVNTMS+nV4MZPbbk62pNeGVJV16Bvojs+GRRXQdh0K0o9s152MsS5uD8PKzXO3dg73jWeK5HD78cprbiyNuuB4104u2UqK9Q6HUUv9cPNNGDha8CAX0pwczVQp8gpaE29gVImxmkG/PtUInlwoev9gLGBtPYzdIPCbEfFbiTXWtNs3W3pO07F7raPuJUmjP0xfUTWChFC14L9v1FLQMyjadYxexdsCvp7kMLkXeomZzOJEVUuhajrMNqYSzlSS0t+3zE6Me86cEkHNsChjubA7CkybJoxW+oyyYO/Fq5zjJb0e+YeTy2L64GLHA5uE8h
sdkimages:
    debug: sha256:17d413462fdfa423a4a18f3863433bdcec7b944ea455bf0e30891a088cbfefe7
    release: ''
sdkimagetags:
    debug: cpphello_arm64v8-debian-no-ssh_bullseye_debug_b085e192-f92c-40e4-a439-612afa79a44a_sdk_image
    release: cpphello_arm64v8-debian-no-ssh_bullseye_release_b085e192-f92c-40e4-a439-612afa79a44a_sdk_image
sdksshaddress:
    debug: null
    release: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common: {}
    debug:
        /home/torizon/cpphello: /cpphello,rw
    release: {}
